steps:
  - block: Release
    prompt: Fill out the details for release
    fields: 
      - text: Name
        key: release-name
      - text: Notes
        key: release-notes
        required: false
      - select: Type
        key: release-type
        default: Major
        options:
          - Major
          - Minor
          - Patch

  - command: release.sh
    label: ":rocket:"
